name: Issue Reply

permissions:
  issues: write

on:
  issues:
    types:
      - labeled

jobs:
  issue-reply:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - label: '🖱️ need reproduce'
            content: |
              你好 @${{ github.event.issue.user.login }}，我们需要你提供一个最小重现实例以便于定位问题，你可以通过以下方式提供：

              - 基于 [xiaohe0601/stackblitz-uniapp](https://github.com/xiaohe0601/stackblitz-uniapp/tree/echarts) 的 echarts 分支的 github 仓库

              - 通过 [StackBlitz](https://stackblitz.com/~/github.com/xiaohe0601/stackblitz-uniapp) 创建一个在线实例（终端执行 `git fetch` 后切换至 echarts 分支）

    steps:
      - name: Reply by label
        if: github.event.label.name == matrix.label
        uses: actions-cool/issues-helper@v3
        with:
          actions: create-comment
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: ${{ matrix.content }}